spring:
  application:
    name: spring-study
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/hanghae
      username: sa
      password: 1234
      idle-timeout: 10000
      maximum-pool-size: 30
      minimum-idle: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true


server:
  error:
    include-exception: true
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
